services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: corporate-soccer-world-cup-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: corporate-soccer-world-cup-jaeger
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: corporate-soccer-world-cup-api
    depends_on:
      - db
      - jaeger
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=${DB_NAME};User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      
      # OpenTelemetry est√°ndar
      - OTEL_SERVICE_NAME=corporate-soccer-world-cup-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "5000:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: corporate-soccer-world-cup-frontend
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    ports:
      - "3000:3000"

volumes:
  sql_data: